apiVersion: v1
kind: ConfigMap
metadata:
  # 配置文件名称
  name: alertmanager-config
  namespace: ns-monitor
  labels:
    k8s-app: alertmanager
data:
  alertmanager.yml: |
    global: 
      resolve_timeout: 5m
    route:
      group_by: ['alertname','cluster','job']
      group_interval: 20s
      group_wait: 20s
      #receiver: default-receiver
      receiver: webhook
      repeat_interval: 1m
    receivers:
    - name: 'webhook'
      webhook_configs:
      #- url: 'http://dingtalk-hook.ns-monitor.svc.cluster.local:8060/dingtalk/webhook1/send' 
      - url: 'http://dingtalk-hook.ns-monitor.svc.cluster.local:5000' 
        send_resolved: true 
    
