---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "alertmanager-data-pv"
  labels:
    name: alertmanager-data-pv
    release: stable
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /test/alertmanager_data
    server: 192.168.65.14

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alertmanager-data-pvc
  namespace: ns-monitor
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      name: alertmanager-data-pv
      release: stable
---
