apiVersion: apps/v1
kind: Deployment
metadata:
  name: dingtalk-hook
  namespace: ns-monitor
spec:
  selector:
    matchLabels:
      app: dingtalk-hook
  template:
    metadata:
      labels:
        app: dingtalk-hook
    spec:
      containers:
      - name: dingtalk-hook
        #image: timonwong/prometheus-webhook-dingtalk
        image: yangpeng2468/alertmanager-dingtalk-hook:v1
        imagePullPolicy: IfNotPresent
        #args:
        #  - --ding.profile=webhook1=https://oapi.dingtalk.com/robot/send?access_token=0dfd64b1d3286a3294eb8ef26ffab3d1a747507118a3da4599e096446d29743c
        ports:
        #- containerPort: 8060
        - containerPort: 5000
          protocol: TCP
        env:
        - name: ROBOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: dingtalk-secret
              key: token
        resources:
          requests:
            cpu: 50m
            memory: 200Mi
          limits:
            cpu: 50m
            memory: 200Mi

---
apiVersion: v1
kind: Service
metadata:
  name: dingtalk-hook
  namespace: ns-monitor
  labels:
    app: dingtalk-hook
spec:
  selector:
    app: dingtalk-hook
  ports:
  - name: hook
    port: 5000
    protocol: TCP
    targetPort: 5000
